# Generated by Django 6.0.3 on 2026-03-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridades',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Nao_urgente', 'Nao_urgente')], default='Nao_urgente', max_length=20),
        ),
    ]
