# Generated by Django 6.0.4 on 2026-04-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'aberta'), ('EM_Andamento', 'em andamento'), ('Concluida', 'concluida'), ('Cancelada', 'cancelada')], default='ABERTA', max_length=20)),
                ('prioridades', models.CharField(choices=[('Urgente', 'Urgente'), ('Nao_urgente', 'Nao_urgente')], default='Nao_urgente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateField()),
            ],
        ),
    ]
